import { NextResponse } from "next/server";
import { requireSystemAdmin } from "../../../../lib/admin";
import { transaction } from "../../../../lib/db";

export async function GET(){const auth=await requireSystemAdmin();if(auth.error)return auth.error;return transaction(async client=>{const [regions,agencies,offices]=await Promise.all([client.query(`SELECT code,name,is_active FROM uars.regions ORDER BY name`),client.query(`SELECT a.code,a.name,a.region_code,a.is_active,r.name region_name FROM uars.agencies a JOIN uars.regions r ON r.code=a.region_code ORDER BY r.name,a.name`),client.query(`SELECT o.id,o.name,o.agency_code,o.is_active,a.name agency_name,a.region_code,r.name region_name FROM uars.offices o JOIN uars.agencies a ON a.code=o.agency_code JOIN uars.regions r ON r.code=a.region_code ORDER BY r.name,a.name,o.name`)]);return NextResponse.json({regions:regions.rows,agencies:agencies.rows,offices:offices.rows});});}

export async function POST(request:Request){const auth=await requireSystemAdmin();if(auth.error)return auth.error;const body=await request.json();const entity=String(body.entity||"");const code=String(body.code||"").trim().toUpperCase();const name=String(body.name||"").trim();if(!name||((entity==="REGION"||entity==="AGENCY")&&!code))return NextResponse.json({error:"Code and name are required."},{status:400});try{return await transaction(async client=>{let id=code;if(entity==="REGION")await client.query(`INSERT INTO uars.regions(code,name) VALUES($1,$2)`,[code,name]);else if(entity==="AGENCY")await client.query(`INSERT INTO uars.agencies(code,region_code,name) VALUES($1,$2,$3)`,[code,String(body.regionCode||"").trim().toUpperCase(),name]);else if(entity==="OFFICE"){const result=await client.query<{id:string}>(`INSERT INTO uars.offices(agency_code,name) VALUES($1,$2) RETURNING id`,[String(body.agencyCode||"").trim().toUpperCase(),name]);id=result.rows[0].id;}else return NextResponse.json({error:"Invalid location type."},{status:400});await client.query(`INSERT INTO uars.admin_audit_events(actor_id,actor_name,action,entity_type,entity_id,details) VALUES($1,$2,'LOCATION_CREATED',$3,$4,$5)`,[auth.user!.id,auth.user!.fullName,entity,id,JSON.stringify({code,name})]);return NextResponse.json({ok:true},{status:201});});}catch(error){const codeValue=(error as {code?:string}).code;if(codeValue==="23505")return NextResponse.json({error:"That code or office already exists."},{status:409});if(codeValue==="23503")return NextResponse.json({error:"Select an existing active parent location."},{status:400});throw error;}}

export async function PATCH(request:Request){const auth=await requireSystemAdmin();if(auth.error)return auth.error;const body=await request.json();const entity=String(body.entity||"");const id=String(body.id||"");const name=String(body.name||"").trim();const active=Boolean(body.isActive);return transaction(async client=>{let result;if(entity==="REGION")result=await client.query(`UPDATE uars.regions SET name=COALESCE(NULLIF($1,''),name),is_active=$2,updated_at=now() WHERE code=$3 RETURNING code`,[name,active,id]);else if(entity==="AGENCY")result=await client.query(`UPDATE uars.agencies SET name=COALESCE(NULLIF($1,''),name),is_active=$2,updated_at=now() WHERE code=$3 RETURNING code`,[name,active,id]);else if(entity==="OFFICE")result=await client.query(`UPDATE uars.offices SET name=COALESCE(NULLIF($1,''),name),is_active=$2,updated_at=now() WHERE id=$3 RETURNING id`,[name,active,id]);else return NextResponse.json({error:"Invalid location type."},{status:400});if(!result.rowCount)return NextResponse.json({error:"Location not found."},{status:404});await client.query(`INSERT INTO uars.admin_audit_events(actor_id,actor_name,action,entity_type,entity_id,details) VALUES($1,$2,'LOCATION_UPDATED',$3,$4,$5)`,[auth.user!.id,auth.user!.fullName,entity,id,JSON.stringify({name,is_active:active})]);return NextResponse.json({ok:true});});}

export async function DELETE(request:Request){const auth=await requireSystemAdmin();if(auth.error)return auth.error;const body=await request.json();const entity=String(body.entity||"");const id=String(body.id||"");try{return await transaction(async client=>{let result;if(entity==="REGION")result=await client.query(`DELETE FROM uars.regions WHERE code=$1 RETURNING code`,[id]);else if(entity==="AGENCY")result=await client.query(`DELETE FROM uars.agencies WHERE code=$1 RETURNING code`,[id]);else if(entity==="OFFICE")result=await client.query(`DELETE FROM uars.offices WHERE id=$1 RETURNING id`,[id]);else return NextResponse.json({error:"Invalid location type."},{status:400});if(!result.rowCount)return NextResponse.json({error:"Location not found."},{status:404});await client.query(`INSERT INTO uars.admin_audit_events(actor_id,actor_name,action,entity_type,entity_id) VALUES($1,$2,'LOCATION_DELETED',$3,$4)`,[auth.user!.id,auth.user!.fullName,entity,id]);return NextResponse.json({ok:true});});}catch(error){if((error as {code?:string}).code==="23503")return NextResponse.json({error:"This location is assigned or contains child records. Deactivate it instead."},{status:409});throw error;}}
